name: Deploy Site

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install npm dependencies
        run: npm ci

      - name: Install LaTeX
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            latexmk

      - name: Cache LaTeX packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/package-lock.json') }}

      - name: Build & Export
        run: |
          npm run build-resume
          cd personal-site
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: personal-site/out
