name: Deploy Site

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 0

      - name: Install Scripts Dependencies
        run: npm ci
        working-directory: scripts

      - name: Install Site Dependencies
        run: npm ci
        working-directory: personal-site

      - name: Install LaTeX
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            latexmk

      - name: Build Site
        run: npm run build

      - name: Disable Jekyll
        run: touch personal-site/out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: personal-site/out
